export const SENTENCE_TRANSLATION_VIEW = "SENTENCE_TRANSLATION_VIEW";
export const SIMPLE_TRANSLATION_VIEW = "SIMPLE_TRANSLATION_VIEW";
export const IRREGULAR_VERB_TRANSLATION_VIEW =
  "IRREGULAR_VERB_TRANSLATION_VIEW";
