name: CI
on:
  push:
    branches: [ develop ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: cd apps/api && npm run prisma:generate

      - name: Run linter
        run: npm run lint -- --no-cache
        env:
          CI: true

      - name: Run Api Tests
        run: cd apps/api && npm run test
        env:
          CI: true

      - name: Build
        run: npm run build
        env:
          CI: true
